- name: Install OpenVPN package
  apt: pkg=openvpn state=installed update_cache=true

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_set: yes

- name: Create certs directory
  file:
    path: /etc/openvpn/certs
    state: directory
    mode: 0700
    owner: root
    group: root
