- name: Install OpenVPN package
  apt:
    pkg: openvpn
    state: present
    update_cache: true
  notify:
    - Enable and start OpenVPN service

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_set: yes

- name: Create certs directory
  file:
    path: /etc/openvpn/certs
    state: directory
    mode: 0700
    owner: root
    group: root
