#
# @all nodes:
#	- OpenVPN package
#	- enable IP forwarding
#
# Centralpoint
#	- copy CA + certificates
#	- copy OpenVPN server configuration
#	- enable OpenVPN service
#	- Network configuration
#
# vRouter
#	- copy OpenVPN client configuration
#	- enable OpenVPN service

# ------------------------------------------------------------------

- hosts: centralpoint
  vars:
    openvpn_name: "centralpoint"
    
  tasks:
    - name: Install OpenVPN
      include_role:
        name: openvpn
        tasks_from: install

    - name: Create custom Diffie-Hellman parameters
      shell: openssl dhparam -out /etc/openvpn/certs/dh2048.pem 2048
      args:
        creates: /etc/openvpn/certs/dh2048.pem

    - name: Create CRL file for OpenVPN
      copy:
        content: ""
        dest: /etc/openvpn/crl.pem
        force: no
        owner: root
        group: root
        mode: 0640

    - name: Restart OpenVPN service
      include_role:
        name: openvpn
        tasks_from: service


# ------------------------------------------------------------------

- hosts: vrouters
  vars:
    openvpn_name: "client"

  roles:
    - role: openvpn
      openvpn_config: "files/client/"
      openvpn_name: "client"
