#
# @all nodes:
#	- OpenVPN package
#	- enable IP forwarding
#
# Centralpoint
#	- copy CA + certificates
#	- copy OpenVPN server configuration
#	- enable OpenVPN service
#	- Network configuration
#
# vRouter
#	- copy OpenVPN client configuration
#	- enable OpenVPN service

# ------------------------------------------------------------------

- hosts: centralpoint
  vars:
    openvpn_name: "centralpoint"
  roles:
    - centos
    - openvpn
    
  tasks:
    - name: Create custom Diffie-Hellman parameters
      shell: openssl dhparam -out /etc/openvpn/certs/dh2048.pem 2048
      args:
        creates: /etc/openvpn/certs/dh2048.pem
      notify:
        -  Enable and start OpenVPN service

    - name: Create CRL file for OpenVPN
      copy:
        content: ""
        dest: /etc/openvpn/crl.pem
        force: no
        owner: root
        group: root
        mode: 0640
      notify:
        -  Enable and start OpenVPN service

    - name: Create client configuration directory
      file:
        path: /etc/openvpn/ccd
        state: directory
        mode: 0700
        owner: root
        group: root
      notify:
        -  Enable and start OpenVPN service

    - name: Copy certificate to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/{{ cert_name }}.crt"
        dest: "/etc/openvpn/certs/CENTRALPOINT.crt"
      notify:
        -  Enable and start OpenVPN service

    - name: Copy key to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/{{ cert_name }}.key"
        dest: "/etc/openvpn/certs/CENTRALPOINT.key"
      notify:
        -  Enable and start OpenVPN service

    - name: Copy CA certificate to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/ca.crt"
        dest: "/etc/openvpn/certs/ca.crt"
      notify:
        -  Enable and start OpenVPN service

# ------------------------------------------------------------------

- hosts: vrouters
  vars:
    openvpn_name: "vrouter"
    centralpoint_file: "{{ conf_dir }}/centralpoint"
    centralpoint_ip: "{{ lookup('file', centralpoint_file) }}"
  roles:
    - centos
    - openvpn

  tasks:
    - name: Copy certificate to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/{{ cert_name }}.crt"
        dest: "/etc/openvpn/certs/vrouter.crt"
      notify:
        - Enable and start OpenVPN service

    - name: Copy key to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/{{ cert_name }}.key"
        dest: "/etc/openvpn/certs/vrouter.key"
      notify:
        - Enable and start OpenVPN service

    - name: Copy CA certificate to OpenVPN
      copy:
        src: "{{ conf_dir }}/certs/ca.crt"
        dest: "/etc/openvpn/certs/ca.crt"
      notify:
        - Enable and start OpenVPN service


