#
# @all nodes:
#	- OpenVPN package
#	- enable IP forwarding
#
# Centralpoint
#	- copy CA + certificates
#	- copy OpenVPN server configuration
#	- enable OpenVPN service
#	- Network configuration
#
# vRouter
#	- copy OpenVPN client configuration
#	- enable OpenVPN service

# ------------------------------------------------------------------


- hosts: vrouters
  vars:
    openvpn_name: "vrouter"
    centralpoint_file: "{{ conf_dir }}/centralpoint"
    centralpoint_ip: "{{ lookup('file', centralpoint_file) }}"
    cert_name: "vrouter-{{ ansible_fqdn }}"
    cert_dir: "/etc/openvpn/certs/"

  roles:
    - centos
    - role: openvpn
      ignore_handlers: true

  tasks:
    - name: CSR
      include: "openssl/csr.yml"

    - name: Delete OpenVPN config (to be caught by the second run)
      file:
        state: absent
        path: "/etc/openvpn/{{ openvpn_name }}.conf"

- hosts: centralpoint
  vars:
    ca_dir: "/root/CA"
    cert_name: "vrouter-{{ hostvars['localhost']['ansible_fqdn'] }}"
    cert_dir: "/etc/openvpn/certs/"
  tasks:
    - name: Copy CSR to CA
      copy: 
        src: "{{ cert_dir }}/{{ cert_name }}.csr"
        dest: "{{ ca_dir }}/certs/{{ cert_name }}.csr"

    - name: Sign
      include: "openssl/sign.yml"

    - name: Copy certificate to OpenVPN
      fetch:
        src: "{{ ca_dir }}/certs/{{ cert_name }}.crt"
        dest: "{{ cert_dir }}/{{ cert_name }}.crt"
        flat: yes

    - name: Copy CA certificate to OpenVPN
      fetch:
        src: "{{ ca_dir }}/ca.crt"
        dest: "{{ cert_dir }}/ca.crt"
        flat: yes

- hosts: vrouters
  vars:
    openvpn_name: "vrouter"
    centralpoint_file: "{{ conf_dir }}/centralpoint"
    centralpoint_ip: "{{ lookup('file', centralpoint_file) }}"
    cert_name: "vrouter-{{ ansible_fqdn }}"
    cert_dir: "/etc/openvpn/certs/"

  roles:
    - openvpn
